Repository FunD-StockProject/StockProject-Frontend, pull requests merged in 2024-11, with the labels that each got.

#19 #17 [docs] add template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/main.yml
  .prettierrc
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/SearchBar.tsx
  src/layout/Mainlayout.tsx
  src/main.tsx
  src/pages/Result.tsx
  src/router/index.tsx
  src/utils/LocalStorage.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  yarn.lock
Labels: 📃 Docs

#21 Feat/#15 home component
  src/layout/Card.tsx
  src/layout/CardList.tsx
  src/pages/Home.tsx
  src/router/index.tsx
  src/utils/ScoreToImage.ts
Labels: ✨ Feature

#26 #15 [feat] Home 화면 카드 종목명 추가
  src/layout/Card/Card.tsx
  src/layout/CardList/CardList.tsx
  src/pages/Home.tsx
  src/ts/Interfaces.ts
Labels: ✨ Feature

#27 #15 [feat] 홈화면 카드 이미지 클릭시 검색 화면 이동
  src/layout/Card/Card.tsx
Labels: ✨ Feature

#28 #15 [feat] 홈화면 카드 리스트 일부 구현
  package-lock.json
  package.json
  src/assets/drop.svg
  src/assets/soar.svg
  src/layout/Card/Card.Style.ts
  src/layout/Card/Card.tsx
  src/layout/CardList/CardList.Style.ts
  src/layout/CardList/CardList.tsx
  src/pages/Home.tsx
  src/ts/Enums.ts
  yarn.lock
Labels: ✨ Feature

#29 #15 [feat] 스타일링 적용 및 메인레이아웃 수정
  src/layout/Card/Card.Style.ts
  src/layout/Mainlayout.tsx
  src/layout/Mainlayout/Mainlayout.Style.ts
  src/layout/Mainlayout/Mainlayout.tsx
  src/router/index.tsx
  src/ts/Types.ts
Labels: ✨ Feature, 🎨 Styling

#31 #15 [fix] esint airbnb 제거
  eslint.config.js
  package-lock.json
  package.json
Labels: 🐞 BugFix

#47 #15 [feat] 홈화면 디자인 수정
  src/layout/Mainlayout/Mainlayout.tsx
  src/pages/Home/Home.Style.ts
Labels: 🎨 Styling

#50 #15 [feat] 홈화면 디자인 반영 및 API 세팅
  src/assets/descentTextDark.svg
  src/assets/descentTextLight.svg
  src/assets/hotTextDark.svg
  src/assets/hotTextLight.svg
  src/assets/popularTextDark.svg
  src/assets/risingTextDark.svg
  src/assets/risingTextLight.svg
  src/layout/CardList/CardList.Style.ts
  src/layout/CardList/CardList.tsx
  src/layout/HotCard/HotCard.Style.ts
  src/layout/HotCard/HotCard.tsx
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
  src/services/api.ts
  src/ts/Constants.ts
  src/ts/Interfaces.ts
Labels: 🎨 Styling, 📬 API

#52 #15 [feat] 디자인 마이너 수정 및 API 세팅 준비
  src/layout/HotCard/HotCard.Style.ts
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
Labels: 🎨 Styling, 📬 API

#53 #15 [feat] 디자인 반영
  src/components/Header.tsx
  src/layout/Card/Card.Style.ts
  src/layout/HotCard/HotCard.Style.ts
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
  src/services/api.ts
Labels: 🎨 Styling

#56 #15 [feat] 화살표 추가
  public/appLogo.svg
  src/components/SearchBar.tsx
  src/layout/CardList/CardList.Style.ts
  src/layout/CardList/CardList.tsx
  src/router/index.tsx
Labels: ✨ Feature

#60 #15 [refactor] styledComponents 객체 형태로 수정
  src/components/Footer/Footer.tsx
  src/controllers/api.ts
  src/layout/CardList/CardList.Style.ts
  src/layout/HotCard/HotCard.Style.ts
  src/layout/Mainlayout/Mainlayout.Style.ts
  src/pages/Home/Home.Style.ts
Labels: 🔨 Refactor

#67 Feat/#15 home component
  package-lock.json
  src/controllers/api.ts
  src/layout/HotCard/HotCard.Style.ts
  src/pages/Home/Home.tsx
  yarn.lock
Labels: 📬 API

#68 #15 [feat] 주식 탭 변경 시 지표 뷰 초기화
  src/layout/CardList/CardList.tsx
  src/pages/Home/Home.tsx
  src/ts/Enums.ts
Labels: ✨ Feature

#69 #15 [feat] 디자인 반영 컴포넌트 수정
  src/components/StockSlotMachine/stockSlotMachine.Style.ts
  src/layout/HotCard/HotCard.Style.ts
  src/pages/Home/Home.tsx
Labels: 🎨 Styling

#74 Feat/#15 home component
  src/assets/leftArrow.svg
  src/assets/rightArrow.svg
  src/layout/CardList/CardList.Style.ts
  src/layout/CardList/CardList.tsx
  src/main.tsx
  vite.config.ts
Labels: 🎨 Styling

#77 Feat/#75 ci cd
  .env
  package.json
  src/controllers/api.ts
Labels: 🌏 Deploy

#78 #75 [feat] 배포세팅
  .env
  package-lock.json
  package.json
  src/controllers/api.ts
  src/main.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🌏 Deploy

#81 #75 [feat] api 단일화
  src/components/SearchBar/SearchBar.tsx
  src/controllers/api.ts
  src/controllers/stock.tsx
Labels: 📬 API

#82 #75 [feat] API 단일화2
  src/components/SearchBar/SearchBar.Prop.ts
Labels: 📬 API

#83 #75 [fea] 배포찐막?
  tsconfig.app.tsbuildinfo
Labels: 🌏 Deploy

#84 Develop
  tsconfig.app.tsbuildinfo
Labels: 🌏 Deploy

#91 #75 [feat] Google Analytics 수정
  public/index.html
  vite.config.ts
Labels: 🌏 Deploy

#92 Develop
  public/index.html
  vite.config.ts
Labels: 🌏 Deploy

#95 #89 [feat] 반응형 초기구현
  package.json
Labels: 🌏 Deploy

#96 #89 [feat] 반응형 구현중
  package-lock.json
  package.json
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vite.config.ts
  yarn.lock
Labels: 🌏 Deploy

#97 #89 [feat] pwa 구현중
  tsconfig.json
Labels: 🌏 Deploy

#98 #89 [feat] netlify 설정 수정
  netlify.toml
Labels: 🌏 Deploy

#99 #89 [feat] plugin 수정
  vite.config.ts
Labels: 🌏 Deploy

#100 #89 [feat] netlify.toml 수정
  dev-dist/registerSW.js
  index.html
  netlify.toml
  package-lock.json
  package.json
  public/index.html
  vite.config.ts
  yarn.lock
Labels: 🌏 Deploy

#105 Feat/#89-pwa
  public/apple-touch-icon-180x180.png
  public/assets/index-BStUxWAW.js
  public/assets/index-C6HsIiKa.css
  public/index.html
  public/manifest.webmanifest
  public/maskable-icon-512x512.png
  public/sw.js
  public/workbox-5ffe50d4.js
Labels: 🎨 Styling

#114 #15 [feat] 홈화면 카드리스트 화살표 위치 변경
  src/layout/CardList/CardList.Style.ts
Labels: 🎨 Styling

#115 #15 [feat] 레이지로딩을 통한 렌더링 최적화
  src/layout/CardList/CardList.tsx
  src/pages/Home/Home.tsx
Labels: 🔨 Refactor

#116 #15 [feat] 점수 등락 구현 중
  src/layout/Card/Card.Style.ts
  src/layout/Card/Card.tsx
  src/layout/CardList/CardList.tsx
  src/pages/Home/Home.tsx
  src/ts/Interfaces.ts
Labels: ✨ Feature

#117 #88 [refactor] react-query 관련 홈화면 리팩토링
  src/main.tsx
  src/pages/Home/Home.tsx
  src/queryClient.ts
  src/ts/Types.ts
Labels: 🔨 Refactor

#118 #88 에러 핸들링 추가
  package-lock.json
  package.json
  src/hooks/useStocks.ts
  src/pages/Home/Home.tsx
  src/router/index.tsx
  yarn.lock
Labels: ✨ Feature

#126 #88 [refactor] 로딩 화면 및 에러 처리 지역화
  src/layout/CardList/CardList.Style.ts
  src/layout/CardList/CardList.tsx
  src/router/index.tsx
Labels: 🔨 Refactor

#131 #88 [refactor] 에러처리 각각의 컴포넌트로 분리
  src/hooks/useStocks.ts
  src/layout/CardList/CardList.tsx
  src/pages/Home/Home.tsx
  src/queryClient.ts
Labels: 🔨 Refactor

#133 #15 [refactor] obeserver iterator 변경
  src/layout/CardList/CardList.tsx
Labels: 🔨 Refactor

#135 #15 [feat] 떡상/떡락 지표 디자인 수정
  src/components/StockCard/StockCard.Style.tsx
  src/components/StockCard/StockCard.tsx
  src/controllers/api.ts
  src/layout/CardList/CardList.tsx
Labels: 🎨 Styling

#137 Feat/#15 home component
  src/components/StockCard/StockCard.Style.tsx
Labels: 🎨 Styling

#140 #37 [feat] 국내/해외 주식 판별 api 수정으로 인한 로직 수정
  .github/workflows/static.yml
  .gitlab-ci.yml
  README.md
  git
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchTitle/SearchTitle.tsx
  src/controllers/api.Type.ts
  src/pages/Search/Search.tsx
  yarn.lock
Labels: ✨ Feature
