Repository FunD-StockProject/StockProject-Frontend, pull requests merged in 2025-05, with the labels that each got.

#316 #315 [feat] 하단 네비게이션바 구현
  src/assets/bottomNav/favorites.svg
  src/assets/bottomNav/home.svg
  src/assets/bottomNav/myPage.svg
  src/assets/bottomNav/shortView.svg
  src/layout/BottomNavigation/BottomNavigation.Style.ts
  src/layout/BottomNavigation/BottomNavigation.tsx
  src/layout/Mainlayout/Mainlayout.tsx
Labels: ✨ Feature

#317 Feat/#315-bottom-nav
  src/assets/bottomNav/favorites.svg
  src/assets/bottomNav/home.svg
  src/assets/bottomNav/lab.svg
  src/assets/bottomNav/myPage.svg
  src/assets/bottomNav/shortView.svg
  src/layout/BottomNavigation/BottomNavigation.Style.ts
  src/layout/BottomNavigation/BottomNavigation.tsx
Labels: 🎨 Styling

#318 #315 [feat] 모의 매수하기 버튼 구현
  src/pages/Search/Search.Style.ts
  src/pages/Search/Search.tsx
Labels: ✨ Feature

#320 Feat/#319 mypage
  src/App.css
  src/assets/icons/checkCircle.svg
  src/assets/icons/pencil.svg
  src/components/PopUp/PWAinfoPopUp/PWAinfoPopUp.style.ts
  src/layout/BottomNavigation/BottomNavigation.Style.ts
  src/layout/BottomNavigation/BottomNavigation.tsx
  src/layout/Header/Header.tsx
  src/layout/Mainlayout/Mainlayout.Style.ts
  src/layout/Mainlayout/Mainlayout.tsx
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/Register/Register.tsx
  src/pages/RegisterDetail/RegisterDetail.tsx
  src/pages/RegisterDone/RegisterDone.tsx
  src/router/index.tsx
Labels: 🐞 BugFix, ✨ Feature

#322 #315 [FIX] 빌드 오류 해결
  src/pages/ShortView/ShortView.tsx
Labels: 🐞 BugFix
