Repository FunD-StockProject/StockProject-Frontend, pull requests merged in 2025-01, with the labels that each got.

#237 #90 [refactor] PWA 및 종목차트별 인간지표 리팩터링
  src/assets/PWA/AddToHome.svg
  src/assets/PWA/RunApp.svg
  src/assets/PWA/ShareButton.svg
  src/components/PWAUsage/iOSSafari/IOSSafari.style.ts
  src/components/PWAUsage/iOSSafari/IOSSafari.tsx
  src/components/PopUp/PWAinfoPopUp/PWAinfoPopUp.style.ts
  src/components/StockTable/StockTable.style.ts
  src/components/StockTable/StockTable.tsx
  src/pages/Usage/Usage.tsx
Labels: 🎨 Styling, 🔨 Refactor

#238 #90 [refactor] 미사용 img 삭제
  src/assets/AddToHome.png
  src/assets/AddToHome.svg
  src/assets/BottomShareButtonTab.png
  src/assets/PWA/PWA.png
  src/assets/RunApp.png
  src/assets/descentSymbol.svg
  src/assets/descentTextDark.svg
  src/assets/descentTextLight.svg
  src/assets/hotTextDark.svg
  src/assets/hotTextLight.svg
  src/assets/logo.svg
  src/assets/popularText.svg
  src/assets/react.svg
  src/assets/risingSymbol.svg
  src/assets/risingTextDark.svg
  src/assets/risingTextLight.svg
  src/assets/인간지표.svg
  src/components/PWAUsage/iOSSafari/IOSSafari.style.ts
  src/components/PopUp/PWAinfoPopUp/PWAInfoPopUp.tsx
Labels: 🔨 Refactor

#239 #90 [refactor] 푸터 아이콘 수정
  src/components/Footer/Footer.Style.ts
  src/components/Footer/Footer.tsx
Labels: 🎨 Styling, 🔨 Refactor

#236 #120 [feat] 로딩 및 에러처리 반응형 구현
  src/components/Component.style.tsx
  src/components/IndexScore/IndexScore.tsx
Labels: 🎨 Styling

#240 #90 [refactor] 공포지수 팝업 멘트 추가 및 상수 관련 리팩토링
  src/components/PopUp/CommonPopUp.style.ts
  src/components/PopUp/FearPopUp/FearPopUp.tsx
  src/controllers/api.ts
  src/controllers/query.ts
  src/pages/Home/Home.tsx
  src/ts/Constants.ts
Labels: 🎨 Styling, 🔨 Refactor

#241 #220 [feat] configure-page 버전 수정
  .github/workflows/static.yml
Labels: 🌏 Deploy, 🔨 Refactor

#247 #90 [feat] 점수 표기 고도화
  src/components/MobileStockCard/MobileStockCard.tsx
  src/components/StockCard/StockCard.Style.tsx
  src/components/StockCard/StockCard.tsx
  src/utils/ScoreConvert.ts
Labels: 🎨 Styling

#249 #219 [feat] 지수 인간지표점수 리팩토링 및 홈화면 수정
  src/components/IndexScore/IndexScore.tsx
  src/components/MobileStockCardGrid/MobileStockCardGrid.tsx
  src/components/PopUp/FearPopUp/FearPopUp.tsx
  src/pages/Search/Search.tsx
Labels: ✨ Feature, 🔨 Refactor

#259 #219 [feat] 키워드 텍스트 수정
  src/components/Keywords/Keywords.tsx
Labels: ✨ Feature

#261 #90 [feat] 타이틀 수정
  index.html
Labels: ✨ Feature

#264 V2.1 배포 (키워드 제외)
  asconfig.json
  command.bat
  index.html
  package-lock.json
  package.json
  public/wasm/wordcloud.wasm
  src/components/Component.style.tsx
  src/components/StockChart/StockChart.tsx
  src/components/StockWordCloud/StockWordCloud.Worker.ts
  src/components/StockWordCloud/StockWordCloud.tsx
  src/utils/wasm/WordCloudWasm.ts
  src/utils/wasm/wordcloud.wasm
  src/utils/wasm/wordcloud.wasm.d.ts
  src/utils/wasm/wordcloud.wat
  src/utils/worker/GenerateWordCloud.ts
  svg.d.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vite.config.ts
  wasm/wordcloud.c
  yarn.lock
Labels: ✨ Feature

#266 #90 [refactor] 디렉토리 리팩토링
  .prettierrc
  src/components/CardList/CardList.tsx
  src/components/CardList/MobileStockCard/MobileStockCard.Style.tsx
  src/components/CardList/MobileStockCard/MobileStockCard.tsx
  src/components/CardList/StockCard/StockCard.Style.tsx
  src/components/CardList/StockCard/StockCard.tsx
  src/components/Common/Common.Type.ts
  src/components/Common/Common.tsx
  src/components/Common/ErrorComponent.tsx
  src/components/Common/LoadingComponent.tsx
  src/components/Component.style.tsx
  src/components/Home/IndexScore/IndexScore.style.ts
  src/components/Home/IndexScore/IndexScore.tsx
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Home/Keywords/Keywords.tsx
  src/components/Home/StockTable/StockTable.style.ts
  src/components/Home/StockTable/StockTable.tsx
  src/components/Search/SearchTitle/SearchTitle.Style.ts
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/components/Search/StockChart/StockChart.Style.ts
  src/components/Search/StockChart/StockChart.Type.ts
  src/components/Search/StockChart/StockChart.tsx
  src/components/Search/StockChart/StockChartCanvas.tsx
  src/components/Search/StockWordCloud/StockWordCloud.Style.ts
  src/components/Search/StockWordCloud/StockWordCloud.Type.ts
  src/components/Search/StockWordCloud/StockWordCloud.Worker.ts
  src/components/Search/StockWordCloud/StockWordCloud.tsx
  src/components/SearchBar/SearchBar.Props.ts
  src/components/SearchBar/SearchBar.tsx
  src/controllers/api.Type.ts
  src/controllers/api.ts
  src/controllers/mock.ts
  src/controllers/query.ts
  src/hooks/useQueryComponent.tsx
  src/hooks/useStocks.ts
  src/layout/Footer/Footer.Style.ts
  src/layout/Footer/Footer.tsx
  src/layout/Header/Header.Style.ts
  src/layout/Header/Header.tsx
  src/layout/Mainlayout/Mainlayout.Props.ts
  src/layout/Mainlayout/Mainlayout.tsx
  src/pages/Home/Home.tsx
  src/pages/Search/Search.tsx
  src/ts/Types.ts
  src/utils/worker/GenerateWordCloud.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vite.config.ts.timestamp-1732210990914-b116dab115a33.mjs
  wasm/wordcloud.c
  yarn.lock
Labels: 🔨 Refactor

#284 #37 [feat] 종목 요약 내용 api 적용
  eslint.config.js
  src/components/CardList/StockCard/StockCard.tsx
  src/components/Search/SearchTitle/SearchTitle.Style.ts
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/controllers/api.Type.ts
  src/controllers/api.ts
  src/controllers/mock.ts
  src/controllers/query.ts
  src/pages/Search/Search.tsx
Labels: 🌏 Deploy, 🎨 Styling, 📬 API

#289 #90 [feat] 전반적인 디자인 반영
  src/components/Common/ContentsItem.Style.ts
  src/components/Home/IndexScore/IndexScore.style.ts
  src/components/Home/StockTable/StockTable.style.ts
  src/components/Home/StockTable/StockTable.tsx
  src/components/Search/StockChart/StockChart.Style.ts
  src/components/Search/StockChart/StockChart.tsx
  src/components/SearchBar/SearchBar.Style.ts
  src/components/StockSlotMachine/StockSlotMachine.tsx
  src/components/StockSlotMachine/stockSlotMachine.Style.ts
  src/layout/Footer/Footer.Style.ts
  src/layout/Footer/Footer.tsx
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
  src/pages/Search/Search.Style.ts
Labels: 🎨 Styling, 🔨 Refactor

#291 #290 [feat] 슬라이드 컴포넌트 구현
  src/assets/icons/leftArrow.svg
  src/assets/icons/rightArrow.svg
  src/components/CardList/CardList.Style.ts
  src/components/CardList/CardList.tsx
  src/components/CardList/MobileStockCard/MobileStockCard.Style.tsx
  src/components/CardList/MobileStockCard/MobileStockCard.tsx
  src/components/CardList/StockCard/StockCard.Style.ts
  src/components/CardList/StockCard/StockCard.Style.tsx
  src/components/CardList/StockCard/StockCard.tsx
  src/components/Common/ContentsItem.Style.ts
  src/components/Home/IndexScore/IndexScore.style.ts
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Home/StockTable/StockTable.style.ts
  src/components/Search/SearchTitle/SearchTitle.Style.ts
  src/components/SlideView/SlideView.Style.ts
  src/components/SlideView/SlideView.tsx
  src/controllers/query.ts
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
  src/pages/Search/Search.Style.ts
  src/pages/Search/Search.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ✨ Feature

#292 #290 [fix] 드래그 버그 해결 및 기타 리팩토링
  src/assets/footer/footer_threads.svg
  src/components/CardList/CardList.tsx
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Home/Keywords/Keywords.tsx
  src/components/Home/StockTable/StockTable.style.ts
  src/components/PopUp/CommonPopUp.style.ts
  src/components/PopUp/FearPopUp/FearPopUp.tsx
  src/components/Search/StockChart/StockChart.tsx
  src/components/SearchBar/SearchBar.Style.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/SlideView/SlideView.Style.ts
  src/components/SlideView/SlideView.tsx
  src/layout/Footer/Footer.Style.ts
  src/layout/Footer/Footer.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#293 V3.11 배포
  src/assets/footer/footer_threads.svg
  src/components/CardList/CardList.tsx
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Home/Keywords/Keywords.tsx
  src/components/Home/StockTable/StockTable.style.ts
  src/components/PopUp/CommonPopUp.style.ts
  src/components/PopUp/FearPopUp/FearPopUp.tsx
  src/components/Search/StockChart/StockChart.tsx
  src/components/SearchBar/SearchBar.Style.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/SlideView/SlideView.Style.ts
  src/components/SlideView/SlideView.tsx
  src/layout/Footer/Footer.Style.ts
  src/layout/Footer/Footer.tsx
Labels: 🐞 BugFix, 🌏 Deploy, 🔨 Refactor

#294 #34 [feat] Disquiet 배지 적용
  src/components/Event/Disquiet.Style.ts
  src/components/Event/Disquiet.svg
  src/components/Event/Disquiet.tsx
  src/components/Event/UpCircle.svg
  src/index.css
  src/layout/Header/Header.Style.ts
  src/layout/Header/Header.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ✨ Feature, :handshake: Accessibility

#295 V3.12 배포
  src/components/Event/Disquiet.Style.ts
  src/components/Event/Disquiet.svg
  src/components/Event/Disquiet.tsx
  src/components/Event/UpCircle.svg
  src/index.css
  src/layout/Header/Header.Style.ts
  src/layout/Header/Header.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: :handshake: Accessibility

#296 #111 [fix] 이동평균선 정수 -> 유리수 변경
  .emotionorderrc
  .prettierrc
  package-lock.json
  package.json
  src/components/Event/Disquiet.Style.ts
  src/components/Home/IndexScore/IndexScore.style.ts
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Search/StockChart/StockChart.Style.ts
  src/components/Search/StockChart/StockChart.tsx
  src/controllers/query.ts
  yarn.lock
Labels: 🐞 BugFix

#297 V3.13 배포
  .emotionorderrc
  .prettierrc
  package-lock.json
  package.json
  src/components/Event/Disquiet.Style.ts
  src/components/Home/IndexScore/IndexScore.style.ts
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Search/StockChart/StockChart.Style.ts
  src/components/Search/StockChart/StockChart.tsx
  src/controllers/query.ts
  yarn.lock
Labels: 🐞 BugFix, 🌏 Deploy

#298 Feat/#90 overall refactor
  .emotionorderrc
  .prettierrc
  package-lock.json
  package.json
  src/components/Event/Disquiet.Style.ts
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Home/StockTable/StockTable.style.ts
  src/components/Search/StockChart/StockChart.Style.ts
  src/components/Search/StockChart/StockChart.tsx
  src/components/SlideView/SlideView.Style.ts
  src/index.css
  src/pages/Home/Home.Style.ts
  yarn.lock
Labels: 🐞 BugFix, ⚙ Setting, ✨ Feature

#301 V3.2.1 배포
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
  yarn.lock
Labels: 🐞 BugFix, 🌏 Deploy

#303 #37 [fix] Title 애니메이션 버벅임 해결
  .prettierrc
  src/components/Search/SearchTitle/SearchTitle.Style.ts
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/layout/Header/Header.Style.ts
  src/layout/Header/Header.tsx
Labels: 🐞 BugFix

#305 #90 [refactor] 디렉토리 정리
  public/_redirects
  public/index.html
  public/manifest.webmanifest
  public/registerSW.js
  public/robots.txt
  public/sw.js
  public/vite.svg
  public/workbox-5ffe50d4.js
  public/workbox-6e150728.js
  src/components/Common/ContentsItem.Style.ts
Labels: 🔨 Refactor

#307 #111 [fix] 차트 줌기능 트랙패드 적용
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/components/Search/StockChart/StockChart.tsx
Labels: 🐞 BugFix, 💻 CrossBrowsing

#306 V 3.2.2
  .prettierrc
  public/_redirects
  public/index.html
  public/manifest.webmanifest
  public/registerSW.js
  public/robots.txt
  public/sw.js
  public/vite.svg
  public/workbox-5ffe50d4.js
  public/workbox-6e150728.js
  src/components/Common/ContentsItem.Style.ts
  src/components/Search/SearchTitle/SearchTitle.Style.ts
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/components/Search/StockChart/StockChart.tsx
  src/components/Search/StockWordCloud/StockWordCloud.Style.ts
  src/components/Search/StockWordCloud/StockWordCloud.tsx
  src/controllers/query.ts
  src/layout/Header/Header.Style.ts
  src/layout/Header/Header.tsx
  src/ts/Constants.ts
  src/utils/worker/GenerateWordCloud.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#308 #90 [refactor] 카드리스트 리팩토링
  src/components/CardList/CardList.tsx
  src/controllers/api.Type.ts
  src/controllers/query.ts
Labels: 🔨 Refactor

#309 #90 [refactor] useQuery 리팩토링
  src/components/CardList/CardList.tsx
  src/components/CardList/StockCard/StockCard.tsx
  src/components/Home/IndexScore/IndexScore.tsx
  src/components/Home/Keywords/Keywords.tsx
  src/components/Home/StockTable/StockTable.tsx
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/controllers/api.Type.ts
  src/controllers/mock.ts
  src/controllers/query.ts
  src/pages/Search/Search.tsx
Labels: 🔨 Refactor
