Repository FunD-StockProject/StockProject-Frontend, pull requests merged in 2025-08, with the labels that each got.

#361 Feat/#331 lab page
  src/components/Lab/StockRecordSheet/ExperimentList/ExpeimentList.Style.ts
  src/components/Lab/StockRecordSheet/ExperimentList/ExperimentDetailBottomSheet.Style.ts
  src/components/Lab/StockRecordSheet/ExperimentList/ExperimentDetailBottomSheet.tsx
  src/components/Lab/StockRecordSheet/ExperimentList/ExpermentList.tsx
  src/components/LabResult/BellCurveChart/BellCurveChart.Style.ts
  src/components/LabResult/BellCurveChart/BellCurveChart.tsx
  src/components/LabResult/BottomSheet/HumanTypeBottomSheet.tsx
  src/components/LabResult/HistorySection/HistorySection.Style.ts
  src/components/LabResult/HistorySection/HistorySection.tsx
  src/components/LabResult/HumanIndexSection/HumanIndexSection.tsx
  src/components/LabResult/InvestmentPatternSection/InvestmentPatternSection.tsx
  src/components/LabResult/LabResult.tsx
  src/pages/Lab/Lab.Style.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ✨ Feature

#373 Feat/#354 short view
  src/assets/icons/cross.svg
  src/assets/icons/heart.svg
  src/assets/icons/magnifier.svg
  src/assets/icons/money.svg
  src/components/Search/StockChart/StockChart.Style.ts
  src/layout/Mainlayout/Mainlayout.tsx
  src/pages/ShortView/ShortView.Style.ts
  src/pages/ShortView/ShortView.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ✨ Feature, 🎨 Styling

#374 #369 [refactor] api 분리
  public/manifest.webmanifest
  src/controllers/api.ts
  src/controllers/api/auth.ts
  src/controllers/api/base.ts
  src/controllers/api/stocks.ts
  src/controllers/query.ts
  src/controllers/query/common.ts
  src/controllers/query/stocks.ts
  src/pages/Favorites/Favorites.Style.ts
Labels: 🔨 Refactor

#383 Feat/#372 origin refactor
  src/assets/flags/korea.png
  src/assets/icons/alarm.svg
  src/assets/icons/bell.svg
  src/assets/icons/info.svg
  src/assets/icons/search.svg
  src/assets/logo/full_logo_white.svg
  src/assets/mask_balloon.png
  src/components/CardList/CardList.Style.ts
  src/components/CardList/CardList.tsx
  src/components/CardList/StockCard/StockCard.Style.ts
  src/components/CardList/StockCard/StockCard.tsx
  src/components/Common/Button.ts
  src/components/Common/Common.Type.ts
  src/components/Common/Common.tsx
  src/components/Home/Banner/Banner.Style.ts
  src/components/Home/Banner/Banner.tsx
  src/components/Home/IndexScore/IndexScore.style.ts
  src/components/Home/IndexScore/IndexScore.tsx
  src/components/Home/Keywords/Keywords.style.tsx
  src/components/Home/Keywords/Keywords.tsx
  src/components/Home/StockTable/StockTable.style.ts
  src/components/Home/StockTable/StockTable.tsx
  src/components/Home/Title/Title.Style.ts
  src/components/NoLoginWrapper/NoLoginWrapper.style.ts
  src/components/PopUp/CommonPopUp.style.ts
  src/components/PopUp/CommonPopUp.tsx
  src/components/PopUp/PWAinfoPopUp/PWAinfoPopUp.style.ts
  src/components/PopUp/ZipyoPopUp/ZipyoPopUp.style.ts
  src/components/PopUp/ZipyoPopUp/ZipyoPopUp.tsx
  src/components/Search/GuageChart/GuageChart.Style.ts
  src/components/Search/GuageChart/GuageChart.tsx
  src/components/Search/SearchTitle/SearchTitle.Style.ts
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/components/StockSlotMachine/StockSlotMachine.tsx
  src/components/StockSlotMachine/stockSlotMachine.Style.ts
  src/constants/stockScore.ts
  src/controllers/api/stocks.ts
  src/controllers/mock.ts
  src/controllers/query/common.ts
  src/controllers/query/stocks.ts
  src/hooks/useModal.tsx
  src/layout/BottomNavigation/BottomNavigation.Style.ts
  src/layout/Mainlayout/Mainlayout.tsx
  src/pages/Favorites/Favorites.tsx
  src/pages/Home/Home.Style.ts
  src/pages/Home/Home.tsx
  src/pages/Search/Search.Style.ts
  src/pages/Search/Search.tsx
  src/styles/themes.ts
  src/ts/Constants.ts
  src/ts/Types.ts
  src/utils/ScoreConvert.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: 🐞 BugFix, ✨ Feature, 🎨 Styling, 📬 API, 🔨 Refactor

#387 #372 [fix] 워드클라우드 가로 우선
  out.wat
  src/utils/wasm/WordCloudWasm.ts
  src/utils/wasm/wordcloud.wasm
  src/utils/worker/GenerateWordCloud.ts
  wasm/README.md
  wasm/wordcloud.c
Labels: 🐞 BugFix

#388 Feat/#354 short view
  src/assets/icons/arrowDropUp.svg
  src/assets/icons/check.svg
  src/assets/short_view_mock.png
  src/assets/swipe_hand.png
  src/components/CardList/StockCard/StockCard.Style.ts
  src/components/CardList/StockCard/StockCard.tsx
  src/components/Search/StockChart/StockChart.Style.ts
  src/components/Search/StockChart/StockChart.tsx
  src/components/ShortView/NeedLogin/NeedLogin.Style.ts
  src/components/ShortView/NeedLogin/NeedLogin.tsx
  src/components/ShortView/Tutorial/Tutorial.Style.ts
  src/components/ShortView/Tutorial/Tutorial.tsx
  src/hooks/useSnapIndex.ts
  src/hooks/useToast.tsx
  src/index.css
  src/layout/Mainlayout/Mainlayout.Style.ts
  src/pages/Search/Search.tsx
  src/pages/ShortView/ShortView.Style.ts
  src/pages/ShortView/ShortView.tsx
  src/pages/ShortView/TinderCard/TinderCard.Style.ts
  src/pages/ShortView/TinderCard/TinderCard.tsx
  src/ts/StockCountry.ts
  src/utils/LocalStorage.ts
Labels: ✨ Feature, 🎨 Styling, 📬 API, 🔨 Refactor, :handshake: Accessibility
