Repository FunD-StockProject/StockProject-Frontend, pull requests merged in 2025-06, with the labels that each got.

#325 #315 [Feat] 숏뷰 틴더카드 라이브러리 도입
  package-lock.json
  package.json
  src/pages/ShortView/ShortView.Style.ts
  src/pages/ShortView/ShortView.tsx
  yarn.lock
Labels: ✨ Feature

#326 #315 [Feat] 디자인 적용
  src/assets/bottomNav/favorites.svg
  src/assets/bottomNav/home.svg
  src/assets/bottomNav/lab.svg
  src/assets/bottomNav/myPage.svg
  src/assets/bottomNav/shortView.svg
  src/layout/BottomNavigation/BottomNavigation.Style.ts
  src/layout/BottomNavigation/BottomNavigation.tsx
  src/pages/ShortView/ShortView.tsx
  src/styles/themes.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: 🎨 Styling

#327 #315 [Feat] 숏뷰 구현중
  src/components/Search/SearchTitle/SearchTitle.tsx
  src/components/SearchBar/SearchBar.Style.ts
  src/components/SearchBar/SearchBar.tsx
  src/layout/BottomNavigation/BottomNavigation.Style.ts
  src/layout/Header/Header.Style.ts
  src/layout/Header/Header.tsx
  src/layout/Mainlayout/Mainlayout.Style.ts
  src/layout/Mainlayout/Mainlayout.tsx
  src/pages/Home/Home.Style.ts
  src/pages/Search/Search.Style.ts
  src/pages/ShortView/Advanced.tsx
  src/pages/ShortView/ShortView.Style.ts
  src/pages/ShortView/ShortView.tsx
  src/router/index.tsx
Labels: ✨ Feature

#328 #315 [fix] 불필요 파일 삭제
  src/pages/ShortView/Advanced.tsx
Labels: 🐞 BugFix

#332 #331 [Feat] 초기 화면 뷰 구현
  src/layout/BottomNavigation/BottomNavigation.tsx
  src/layout/Header/Header.tsx
  src/layout/Mainlayout/Mainlayout.tsx
  src/pages/Lab/Lab.Style.ts
  src/pages/Lab/Lab.tsx
  src/pages/ShortView/ShortView.Style.ts
  src/router/index.tsx
  src/styles/themes.ts
Labels: ✨ Feature

#333 #331 [fix] 빌드 오류 해결
  src/pages/Lab/Lab.Style.ts
  src/pages/ShortView/ShortView.Style.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: 🐞 BugFix

#334 #331 [Feat] 종목 선택까지 뷰 구현
  src/assets/backLogo.svg
  src/assets/koreaFlag.svg
  src/assets/usFlag.svg
  src/components/Lab/Common.Style.ts
  src/components/Lab/Intro/Intro.Style.ts
  src/components/Lab/Intro/Intro.tsx
  src/components/Lab/MarketSelection/MarketSelection.Style.ts
  src/components/Lab/MarketSelection/MarketSelection.tsx
  src/components/Lab/Result/Result.Style.ts
  src/components/Lab/Result/Result.tsx
  src/components/Lab/StockPurchase/StockPurchase.Style.ts
  src/components/Lab/StockPurchase/StockPurchase.tsx
  src/components/Lab/StockSearch/StockSearch.Style.ts
  src/components/Lab/StockSearch/StockSearch.tsx
  src/components/Lab/StockSelection/StockSelection.Style.ts
  src/components/Lab/StockSelection/StockSelection.tsx
  src/pages/Lab/Lab.Style.ts
  src/pages/Lab/Lab.tsx
  src/router/index.tsx
Labels: ✨ Feature

#335 #331 [Feat] 실험실 화면 구현
  package-lock.json
  src/assets/icons/cancel.svg
  src/assets/icons/check.svg
  src/assets/icons/purchaseCheck.svg
  src/assets/icons/rightArrow.svg
  src/assets/icons/search.svg
  src/assets/icons/uncheck.svg
  src/components/Lab/Common.Style.ts
  src/components/Lab/MarketSelection/MarketSelection.tsx
  src/components/Lab/Result/Result.Style.ts
  src/components/Lab/Result/Result.tsx
  src/components/Lab/StockPurchase/StockPurchase.Style.ts
  src/components/Lab/StockPurchase/StockPurchase.tsx
  src/components/Lab/StockSearch/StockSearch.Style.ts
  src/components/Lab/StockSearch/StockSearch.tsx
  src/components/Lab/StockSelection/StockSelection.Style.ts
  src/components/Lab/StockSelection/StockSelection.tsx
  src/components/SearchBar/SearchBar.tsx
  src/pages/ShortView/ShortView.tsx
  src/router/index.tsx
  src/styles/themes.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#338 #331 [Feat] 관심 산업 최대 선택 개수 구현
  src/components/Lab/StockSelection/StockSelection.tsx
Labels: ✨ Feature

#340 #331 [Feat] 화면 변동 사항 반영
  src/assets/icons/warning.svg
  src/components/Lab/Common.Style.ts
  src/components/Lab/MarketSelection/MarketSelection.tsx
  src/components/Lab/Result/Result.tsx
  src/components/Lab/StockPurchase/StockPurchase.Style.ts
  src/components/Lab/StockPurchase/StockPurchase.tsx
  src/components/Lab/StockSearch/StockSearch.Style.ts
  src/components/Lab/StockSearch/StockSearch.tsx
  src/components/Lab/StockSelection/StockSelection.Style.ts
  src/components/Lab/StockSelection/StockSelection.tsx
Labels: ✨ Feature

#341 #331 [Feat] 구분선 추가
  src/components/Lab/Common.Style.ts
  src/components/Lab/StockPurchase/StockPurchase.Style.ts
  src/components/Lab/StockPurchase/StockPurchase.tsx
  src/components/Lab/StockSelection/StockSelection.Style.ts
  src/components/Lab/StockSelection/StockSelection.tsx
  src/router/index.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: 🎨 Styling

#346 #343 [feat] 카카오 로그인
  .env
  src/controllers/api.ts
  src/pages/Callback/Callback.tsx
  src/pages/Login/Login.tsx
  src/router/index.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vite.config.ts
Labels: 📬 API

#347 #343 [fix] redirect Url 동적 반영
  src/pages/Login/Login.tsx
Labels: 🐞 BugFix, 💻 CrossBrowsing

#348 #331 [Feat] 종목검색시 네비게이션바 비활성화
  src/components/Lab/StockSearch/StockSearch.tsx
  src/components/Lab/StockSelection/StockSelection.Style.ts
  src/layout/BottomNavigation/BottomNavigation.tsx
Labels: ✨ Feature
